/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TamuRouteImport } from './routes/tamu'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporDewasaRouteImport } from './routes/lapor.dewasa'
import { Route as LaporAnakRouteImport } from './routes/lapor.anak'

const TamuRoute = TamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporDewasaRoute = LaporDewasaRouteImport.update({
  id: '/lapor/dewasa',
  path: '/lapor/dewasa',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporAnakRoute = LaporAnakRouteImport.update({
  id: '/lapor/anak',
  path: '/lapor/anak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/tamu': typeof TamuRoute
  '/lapor/anak': typeof LaporAnakRoute
  '/lapor/dewasa': typeof LaporDewasaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/tamu': typeof TamuRoute
  '/lapor/anak': typeof LaporAnakRoute
  '/lapor/dewasa': typeof LaporDewasaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/tamu': typeof TamuRoute
  '/lapor/anak': typeof LaporAnakRoute
  '/lapor/dewasa': typeof LaporDewasaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/tamu'
    | '/lapor/anak'
    | '/lapor/dewasa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/tamu'
    | '/lapor/anak'
    | '/lapor/dewasa'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/tamu'
    | '/lapor/anak'
    | '/lapor/dewasa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  TamuRoute: typeof TamuRoute
  LaporAnakRoute: typeof LaporAnakRoute
  LaporDewasaRoute: typeof LaporDewasaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tamu': {
      id: '/tamu'
      path: '/tamu'
      fullPath: '/tamu'
      preLoaderRoute: typeof TamuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor/dewasa': {
      id: '/lapor/dewasa'
      path: '/lapor/dewasa'
      fullPath: '/lapor/dewasa'
      preLoaderRoute: typeof LaporDewasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor/anak': {
      id: '/lapor/anak'
      path: '/lapor/anak'
      fullPath: '/lapor/anak'
      preLoaderRoute: typeof LaporAnakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  TamuRoute: TamuRoute,
  LaporAnakRoute: LaporAnakRoute,
  LaporDewasaRoute: LaporDewasaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
